import '../site_config.dart';
import '../site_customization.dart';

const bbzlbInkCustomization = SiteCustomization(
  linkSecurityConfig: LinkSecurityConfig(
    enableExitConfirmation: true,
    internalDomains: [
      'bb.zlb.ink',
      '*.bb.zlb.ink',
      'localhost',
      '*.local',
      '^127(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}',
      '^10(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}',
      '^169\\.254(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){2}',
      '^192\\.168(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){2}',
      '^172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){2}',
    ],
    riskyDomains: [
      'bit.ly',
      'tinyurl.com',
      't.co',
      'goo.gl',
      'ow.ly',
      'buff.ly',
      'adf.ly',
      'short.link',
      '*.short.link',
      'tiny.cc',
      'is.gd',
      'cli.gs',
      'pic.gd',
      'dwarfurl.com',
      'yfrog.com',
      'migre.me',
      'ff.im',
      'tiny.pl',
      'url4.eu',
      'tr.im',
      'twit.ac',
      'su.pr',
      'twurl.nl',
      'snipurl.com',
      'budurl.com',
      'short.to',
      'ping.fm',
      'digg.com',
      'post.ly',
      'just.as',
      'bkite.com',
      'snipr.com',
      'fic.kr',
      'loopt.us',
      'doiop.com',
      'twitthis.com',
      'htxt.it',
      'alturl.com',
      'redirx.com',
      'digbig.com',
      'short.ie',
      'u.mavrev.com',
      'kl.am',
      'wp.me',
      'rubyurl.com',
      'om.ly',
      'to.ly',
      'bit.do',
      'lnkd.in',
      'db.tt',
      'qr.ae',
      'bitly.com',
      'cur.lv',
      'ity.im',
      'q.gs',
      'po.st',
      'bc.vc',
      'u.to',
      'j.mp',
      'buzurl.com',
      'cutt.us',
      'u.bb',
      'yourls.org',
      'x.co',
      'prettylinkpro.com',
      'scrnch.me',
      'filoops.info',
      'vzturl.com',
      'qr.net',
      '1url.com',
      'tweez.me',
      'v.gd',
      'link.zip',
    ],
  ),
);

const bbzlbInkSite = SiteConfig(
  baseUrl: 'https://bb.zlb.ink',
  primaryHost: 'bb.zlb.ink',
  allowedHosts: [
    'bb.zlb.ink',
    'www.bb.zlb.ink',
    '*.bb.zlb.ink',
  ],
  siteCustomization: bbzlbInkCustomization,
  features: SiteFeatures(
    enableCdk: false,
    enableLdc: false,
    enableConnectStats: false,
    enableReward: false,
    useWebViewLoginOnly: true,
  ),
);
